name: azure
description: Azure dart package
version: 0.0.2
repository: https://github.com/tyler-jewell/azure
issue_tracker: https://github.com/tyler-jewell/azure/issues

environment:
  sdk: ^3.1.3

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.25.5
  very_good_analysis: ^5.1.0
